function DP = PROBABILITY_OF_DETECTION_OF(SENSOR_INDEX,UU,SDM,ENERGY_INIT,ENERGY,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA)
    %--------  PROBABILITY OF EACH SENSOR -----------------------
ALL_TARGETS = targets_covered_by_sensor(SDM,SENSOR_INDEX,SENSING_RANGE);
TARGETS_UNCOVERED = intersect(ALL_TARGETS,UU);
%disp('----------------------------------------------------------------');
%si = sprintf('SENSOR %d',SENSOR_INDEX); disp(si);
DP = 0.00;

for i=1:length(TARGETS_UNCOVERED)
    TARGET = TARGETS_UNCOVERED(i);
    PROBABILITY_DETECTION = DETECTION_PROBABILITY(TARGET,SENSOR_INDEX,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA);
    SENSORS_COVERING_TARGET = neighbours_sensor(SDM,TARGET,SENSING_RANGE);
    DP_SUM = 0;
    for t=1:length(SENSORS_COVERING_TARGET)
        DP_OF = DETECTION_PROBABILITY(TARGET,SENSORS_COVERING_TARGET(t),SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA);
        DP_SUM = DP_SUM + DP_OF;
    end
    P_cond = PROBABILITY_DETECTION / DP_SUM * (ENERGY(SENSOR_INDEX)/ENERGY_INIT);
    DP = DP + P_cond;
end
% Finally !
DP = DP * (1/length(UU));
end