function DETECT_PROBA = CUMULATIVE_DETECTION_PROBABILITY(TARGETS,SENSOR_INDEX,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA,NEIGH)
    DETECT_PROBA = 0;
    for i=1:length(TARGETS)
        ODP = OVERALL_DETECTION_PROBABILITY(TARGETS(i),SENSOR_INDEX,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA,NEIGH);
        DETECT_PROBA = DETECT_PROBA + ODP;
    end
    DETECT_PROBA = DETECT_PROBA * (1 / length(TARGETS));
end