function DETEC_PROBA = DETECTION_PROBABILITY(TARGET_INDEX,SENSOR_INDEX,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA)
    %aa = sprintf('DETECTION PROABILITY CALCULATION : SENSOR %d : TARGET %d',SENSOR_INDEX,TARGET_INDEX); disp(aa);
    X = [SENSORS_MAT(2,SENSOR_INDEX),SENSORS_MAT(3,SENSOR_INDEX); TARGETS_MAT(2,TARGET_INDEX),TARGETS_MAT(3,TARGET_INDEX)];
    DISTANCE = pdist(X,'euclidean');
    %dd = sprintf('DISTANCE = %f',DISTANCE); disp(dd);
    if DISTANCE <= SENSING_RANGE
        DETEC_PROBA = exp(-(ALPHA)*DISTANCE);
    else 
        DETEC_PROBA = 0.0;
    end
    %dp = sprintf('DETECT PROBA = %f',DETEC_PROBA); disp(dp);

end