function MAT = MATRIX_OF_DETECTION(NB_SENSORS,NB_TARGETS,SDM,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA)
MAT = zeros(NB_SENSORS,NB_TARGETS);

for s_ind=1:NB_SENSORS
    SENSOR_ID = s_ind;
    COVERED_TARGETS = targets_covered_by_sensor(SDM,SENSOR_ID,SENSING_RANGE);
    for t_ind=1:length(COVERED_TARGETS)
        TARGET_ID = COVERED_TARGETS(t_ind);
        MAT(SENSOR_ID,TARGET_ID) = DETECTION_PROBABILITY(TARGET_ID,SENSOR_ID,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA);
    end
end
end