function [PROB_LIST MAX_P SENSOR_ID] = MAXIMUM_DETECTION_PROBABILITY(SENSORS,UU,SDM,ENERGY_INIT,ENERGY,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA)
    %-------------- MAXIMUM PROFIT SENSOR ------------------
PROB_LIST = zeros(0);
SENSORS_LIST = zeros(0);
k = 1;
for i = 1:length(SENSORS)
    SENSORS_LIST(k) = SENSORS(i);
    PROB_LIST(k) = PROBABILITY_OF_DETECTION_OF(SENSORS(i),UU,SDM,ENERGY_INIT,ENERGY,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA);
    k = k+1;
end
[MAX_P INDEX] = max(PROB_LIST);
SENSOR_ID = SENSORS_LIST(INDEX);
end