function DETECT_PROBA = OVERALL_DETECTION_PROBABILITY(TARGET_INDEX,SENSORS,SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA,NEIGH)
    NN = sensors_covering_target(TARGET_INDEX,NEIGH);
    NEIGH_SENSORS = intersect(NN,SENSORS);
    DP2 = 1;
    for i=1:length(NEIGH_SENSORS)
        DP1 = 1 - DETECTION_PROBABILITY(TARGET_INDEX,SENSORS(i),SENSORS_MAT,TARGETS_MAT,SENSING_RANGE,ALPHA);
        DP2 = DP2 * DP1;
    end
    DETECT_PROBA = 1 - DP2;
end