function PROBABILITY = PROBABILITY_OF_(SENSOR_INDEX,UU,SDM,RANGE,ENERGY_INIT,ENERGY)
%--------  PROBABILITY OF EACH SENSOR -----------------------
ALL_TARGETS = targets_covered_by_sensor(SDM,SENSOR_INDEX,RANGE);
TARGETS_UNCOVERED = intersect(ALL_TARGETS,UU);
%TARGETS_COVERED = setdiff(ALL_TARGETS,TARGETS_UNCOVERED);
PROBABILITY = 0.00;
for i=1:length(TARGETS_UNCOVERED)
    TARGET = TARGETS_UNCOVERED(i);
    SENSORS_COVERING_TARGET = neighbours_sensor(SDM,TARGET,RANGE);
   % NUMBER_OF_NODES_COVERING_ZIS_TARGET = length(SENSORS_COVERING_TARGET);
    PB_SUM = 0.0;
    for t=1:length(SENSORS_COVERING_TARGET)
        SENSOR_ID = SENSORS_COVERING_TARGET(t);
        if ENERGY(SENSOR_ID) == 0
            PB_SUM = PB_SUM + 0;
        else
            PB_SUM = PB_SUM + ENERGY(SENSOR_INDEX)/ENERGY(SENSOR_ID);
        end
    end
    P_cond = 1 / PB_SUM;
    PROBABILITY = PROBABILITY + P_cond;
end
PROBABILITY = (PROBABILITY * (1 / length(UU)));
end