close all
clear all
clc
NB_NODES = 100;
NB_TARGETS = 20;
LENGTH_FIELD = 20;
ENERGY_INIT = 5;
RUNTIME = 2.5;

RESULT_SP = zeros(0,0);
RESULT_PP = zeros(0,0);
RESULT_ZB = zeros(0,0);
NODES_TO_SIMULATE =  [10 ];
RANGE = [ 50 100 150 200 250 300];
NODES = [50 100];
TARGETSS = [5];
MIN_COVERAGE = 0;
MAX_COVERAGE = 0;
AVG_COVERAGE = 0;

k_sp = 1;
k_zb = 1;
k_pp = 1;
k_cr = 1;
        [SENSORS_MATRIX, TARGETS_MATRIX, XCOORs, YCOORs, ENERGY] = generate_topology(10,5,LENGTH_FIELD,ENERGY_INIT);
        %[RESULT_MP, MIN_COVERAGE, AVG_COVERAGE, MAX_COVERAGE] = DISJOINT_MPTC_SIMULATION(10,5,LENGTH_FIELD,SENSORS_MATRIX,TARGETS_MATRIX,ENERGY_INIT,ENERGY,RUNTIME);
        disp(size(MIN_COVERAGE));
        disp(SENSORS_MATRIX);